### ISSUE TITLE
Some icons sometimes not visible when threads are open

### ISSUE THREAD

**Issue by Hate9** [doggybootsy/FluentCord#10]
When the window is too small and a thread is open in "preview" mode, a number of icons (including the settings icon) do not display:
![threads2](https://user-images.githubusercontent.com/4684153/133441282-9a546bcd-0115-4a68-aa49-c3674ce03c8e.png)
And when the window is not too small, the thread appears with an ugly transparent gap between it and the main window:
![threads3](https://user-images.githubusercontent.com/4684153/133441579-2ef54394-baaa-481d-8516-caf3bd18795f.png)

**Comment by doggybootsy** [comment]
I'll look at this later
