### ISSUE TITLE
settings  bug

### ISSUE THREAD

**Issue by Fdr3iZzz** [doggybootsy/FluentCord#5]
Hey man, I really like your theme but some things arnt as intended (probably xD)
The hitbox of the three dots (1) is not correctly placed when on a discord server.
Further more the three buttons are not working when on a discord server.  Lastly you cant really move the window around and there is probably a pixel mistake (2).
I hope that helps you and you wil be able to fix those things. So far I really like your theme

1: ![Unbenannt](https://user-images.githubusercontent.com/37617308/126245980-25e59c1a-ab94-4c4c-8102-f97c156d76e7.PNG)

2: ![Unbenan1nt](https://user-images.githubusercontent.com/37617308/126246052-8a342ac1-4210-429f-9b7d-b2a2e1c7e1f8.PNG)

**Comment by doggybootsy** [comment]
I won't be able to fix these for a couple days. 
But the last two I won't be able to reproduce since I use OS X using the emulation plugin.

**Comment by doggybootsy** [comment]
I do have a local fix (will push soon) so im gonna close
