### ISSUE TITLE
How to download the theme?

### ISSUE THREAD

**Issue by maicol07** [doggybootsy/FluentCord#7]
If I try to load Fluentcord.theme.css I get _I changed my repository to a new format, redownload the theme_. However, I've tried to download it from BetterDiscord and from the repo but didn't work...

**Comment by doggybootsy** [comment]
From here [SOURCE](https://raw.githubusercontent.com/doggybootsy/FluentCord/main/support/Fluentcord.theme.css )

**Comment by doggybootsy** [comment]
Shouldve specified more

**Comment by maicol07** [comment]
It doesn't work on BetterDiscord... I enable the theme and it doesn't change anything...

**Comment by maicol07** [comment]
It seems the compiled CSS URL is wrong since it returns 404. Works if I use the URL from [GitHack](https://raw.githack.com/):
https://rawcdn.githack.com/doggybootsy/FluentCord/19ced665ca80bc2448b057f4961328b1f65773c2/dist/compiled.css

**Comment by doggybootsy** [comment]
i see i mustve missed up

**Comment by doggybootsy** [comment]
i updated it, it was from me putting the name as `Fluentcord` not `FluentCord`
