### ISSUE TITLE
Thread labels display wrong

### ISSUE THREAD

**Issue by Hate9** [doggybootsy/FluentCord#9]
![threads](https://user-images.githubusercontent.com/4684153/133440490-f994b16c-eb96-4fe5-b55b-4804c378b22f.png)
Threads display with the text in front of the thread icon.
They should, presumably, display with the text pushed to the side by the icon, like the other channels do with their icons.
It's not a major issue, but it is a shame in an otherwise pretty theme

**Comment by doggybootsy** [comment]
Should be fixed

**Comment by doggybootsy** [comment]
will fix threads fully later
